### ISSUE TITLE
Change license to GPLv3 or later

### ISSUE THREAD

**Issue by saraedum** [flatsurf/veerer#25]
Currently, the license is GPLv3. We should change it to GPLv3 or later. Or even GPLv2 or later.

What do you think?

We need to check that the authors agree to such a change:

* [x] videlec
* [x] Mark Bell
* [x] Saul Schleimer
* [x] slel
* [x] fchapoton
* [x] saraedum

**Comment by videlec** [comment]
So GPL v2 (or later).

**Comment by saraedum** [comment]
@MarkCBell @saulsch @fchapoton are you fine with us changing the license of veerer from GPLv3 (exact) to GPLv2 or later?

**Comment by fchapoton** [comment]
ok for me

**Comment by saulsch** [comment]
Dear Julian -

> @MarkCBell <https://github.com/MarkCBell> @saulsch
> <https://github.com/saulsch> @fchapoton <https://github.com/fchapoton>
> are you fine with us changing the license of veerer from GPLv3 (exact) to
> GPLv2 or later?
>
Sure - that is fine.

I have a slight preference for public domain (instead of GPL) but you can
ignore me. :)

best,

saul

**Comment by MarkCBell** [comment]
That's fine by me. Go for it. 

Best,
Mark
